---
- name: 'Install wget'
  yum: name=wget state=latest

- name: 'Download Python PIP'
  tags: 'aws-cli'
  command: wget https://bootstrap.pypa.io/get-pip.py -P /tmp
  
- name: 'Install Python PIP'
  tags: 'aws-cli'
  command: python /tmp/get-pip.py

- name: 'Remove get-pip.py file'
  tags: 'aws-cli'
  command: rm /tmp/get-pip.py

- name: 'Install AWS CLI' 
  tags: 'aws-cli'
  pip: name=awscli

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  file: >
    path={{ home_dir }}/.aws
    state=directory
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  template: >
    src=aws_cli_config.j2
    dest={{ home_dir }}/.aws/credentials
    mode=0644

- name: 'Copy aws-s3-sync unit files'
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: 'aws-s3-sync.service', dest: '/etc/systemd/system/', mode: '0644' }
    - { src: 'aws-s3-sync.timer', dest: '/etc/systemd/system/', mode: '0644' }

- name: 'Enable aws-s3-sync unit'
  shell: systemctl enable aws-s3-sync.timer

- name: 'Start aws-s3-sync unit'
  shell: systemctl start aws-s3-sync.timer
